### PR TITLE
Smaller bundle for speed increase

### PR DESCRIPTION
**Pull request by robertdxyz**

### CODE REVIEW

**Comment by vtemian** [comment]
lgtm

**Comment by robertdxyz** [comment]
Build time
1m41s vs 32s

Uncompressed home page size
3.2 MB vs 1.4 MB

app.js
2.7M vs 916K

@palcu @vtemian @hurrycane

**Comment by palcu** [comment]
That was fast. Mai trag si eu vreo 2 issue-uri d-astea si dam raspunsul pe Twitter.

**Comment by robertdxyz** [comment]
Build time
1m41s vs 32s vs 25s

Uncompressed home page size
3.2 MB vs 1.4 MB vs 1.4MB

app.js
2.7M vs 916K vs 892K

@palcu @vtemian @hurrycane

**Pull request merged**
