### PR TITLE
Update menu a little bit. #323

### PR DESCRIPTION
**Pull request by vtemian**

### CODE REVIEW

**Comment by vtemian** [comment]
@robertdolca CR pls

**Comment by robertdxyz** [comment]
Nu mai merge loginul. Nu se face ajax requestul

**Comment by vtemian** [comment]
Pe local merge.
Pe stage primesc `POST https://api.dev.infoeducatie.ro/v1/sign_in net::ERR_INSECURE_RESPONSE`

**Comment by robertdxyz** [comment]
LGTM

**Comment by palcu** [comment]
LGTM

**Pull request merged**
